services:
  db:
    image: postgres:16-alpine
    container_name: lazaro-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lazarodb
      POSTGRES_USER: edigesadmin
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/initdb.sh:/docker-entrypoint-initdb.d/00_initdb.sh:ro
      - ./sql:/docker-entrypoint-initdb.d/sql:ro
    networks:
      - ediges

volumes:
  pgdata:

networks:
  ediges:
    name: ediges
